// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ProcessorCSV.DAL.Entities
{
    public partial class Document
    {
        public Document()
        {
            DocumentItems = new HashSet<DocumentItem>();
        }

        public Guid Id { get; set; }
        public string DocumentName { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? LastModified { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<DocumentItem> DocumentItems { get; set; }
    }
}